version: "3.7"

services:
  db:
    build:
      context: ./services/api/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/api_dev
    volumes:
      - ./services/api:/app

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - "./services/client:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3001:8080
    environment:
      NODE_ENV: development
    depends_on:
      - api

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - api
