FROM ruby:2.3.8-alpine

RUN apk add --update build-base nodejs-current postgresql-dev tzdata
RUN gem install rails -v '5.2.2'

WORKDIR /app
ADD Gemfile Gemfile.lock /app/
RUN bundle install

ADD . .
CMD ["puma"]